### ISSUE TITLE
'google' not defined error

### ISSUE THREAD

**Issue by albertorealfdez** [psykolm22/ng2-google-place-autocomplete#1]
Hello,

First of all, thank you very much for creating this tool and specially for the stable version of Angular 2, what is awesome and useful. 

Well, I am using it in my Angular 2 and Angular Universal application with webpack, and it works perfectly, however I get an error in the log that says: `ReferenceError: google is not defined`

The complete error log is: 

```
EXCEPTION: google is not defined
ORIGINAL STACKTRACE:
ReferenceError: google is not defined
    at GooglePlaceDirective.ngOnInit (/vagrant/universal-workshop/node_modules/ng2-google-place-autocomplete/lib/ng2-google-place-directive.js:41:33)
    at AppView._View_SearchAutocompleteComponent0.detectChangesInternal (SearchAutocompleteComponent.ngfactory.js:105:89)
    at AppView.detectChanges (/vagrant/universal-workshop/node_modules/@angular/core/bundles/core.umd.js:9566:18)
    at AppView.detectViewChildrenChanges (/vagrant/universal-workshop/node_modules/@angular/core/bundles/core.umd.js:9592:23)
    at AppView._View_HomeSearchComponent0.detectChangesInternal (HomeSearchComponent.ngfactory.js:362:8)
    at AppView.detectChanges (/vagrant/universal-workshop/node_modules/@angular/core/bundles/core.umd.js:9566:18)
    at AppView.detectViewChildrenChanges (/vagrant/universal-workshop/node_modules/@angular/core/bundles/core.umd.js:9592:23)
    at AppView._View_HomeComponent0.detectChangesInternal (HomeComponent.ngfactory.js:135:8)
    at AppView.detectChanges (/vagrant/universal-workshop/node_modules/@angular/core/bundles/core.umd.js:9566:18)
    at AppView.detectViewChildrenChanges (/vagrant/universal-workshop/node_modules/@angular/core/bundles/core.umd.js:9592:23)
[ReferenceError: google is not defined]

```

I have followed all the usage steps indicated in the documentation except for the systemjs part, as I am using webpack, where I suspect  the error resides. I would like to know if this is the reason or maybe it is another one, and if there is a solution to it.

Thank you in advance.

Regards.

**Comment by psykolm22** [comment]
Hello, thank you for your intervention.
I forgot to mention the importance of adding the link to the google api in index.html (add in [doc](https://github.com/psykolm22/ng2-google-place-autocomplete#dont- forget-to-add-google-api-in-your-indexhtml))

The library has been migrated to the config Webpack (angular cli best practices) and the documentation should be up to date .

Try to uninstall and install ng2-google-place-autocomplete and it will work.

Regards.

**Comment by albertorealfdez** [comment]
Hello,

Thank you for the quick solution, but unfortunately it did not work. I already added the link to the Google API the first time, since it did not work at all without it and I saw it in your `index.html`. 

So re-installing the library I get the same error than before. I am not sure if I should do something more, maybe trying to add this library to webpack, as I mentioned before, but I don't know exactly how.

Regards.

**Comment by psykolm22** [comment]
Hello , 

did you use angular cli ? i just make a test with a new angular cli project , install the library and it works. Did you put the google link in the main index.html ?  Here is the steps i do just after ng new  1) put the google api link in the main index.html at the root of your app like here  

```
<head>
  <meta charset="utf-8">
  <title></title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
   <script  type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>
</head>
<body>
  <app-root>Loading...</app-root>
</body>
```

2) import in app.module.ts
`import {GooglePlaceModule} from 'ng2-google-place-autocomplete'
imports: [
    ...
    GooglePlaceModule
  ],`

3) Optional: create options and other in app.component.ts `
 public options = {types: [],componentRestrictions: { country: 'FR' }}
    getAddress(place:Object) {       
           console.log("Address", place);
       }` 

Verify that google api is load like you can see in this image
![test](https://cloud.githubusercontent.com/assets/11921919/19261585/805d741c-8f92-11e6-8255-6265ded89279.gif)

**Comment by albertorealfdez** [comment]
Hello, 

I solved it, what a silly thing. It was just where the Google API link is placed, I put it at the end of the `body`, after `app` selector., since there is one more script placed there. Moving it to the `head` solved the problem.

Thank you very much.

Regards.
